version: "3.9"

services:
  bot:
    build: .
    container_name: wb_notify_bot
    command: ["python", "main.py"]
    env_file: .env
    depends_on:
      - db
      - redis
      - nats
    restart: always

  worker:
    build: .
    container_name: wb_notify_worker
    command: ["taskiq", "taskiq_worker:broker"]
    env_file: .env
    depends_on:
      - bot
      - db
      - redis
      - nats
    restart: always

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"  # Monitoring
    restart: always

volumes:
  pgdata:
